export const mockCategories = [
  {
    _id: '1',
    name: 'Tops',
    slug: 'tops',
    description: 'Elevated essentials for every occasion',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
  },
  {
    _id: '2',
    name: 'Bottoms',
    slug: 'bottoms',
    description: 'Refined silhouettes from denim to tailored',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
  },
  {
    _id: '3',
    name: 'Outerwear',
    slug: 'outerwear',
    description: 'Statement pieces for layered looks',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
  },
  {
    _id: '4',
    name: 'Dresses',
    slug: 'dresses',
    description: 'From minimal to bold, day to night',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
  },
  {
    _id: '5',
    name: 'Accessories',
    slug: 'accessories',
    description: 'The finishing touch to complete your look',
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800',
  },
  {
    _id: '6',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Step forward in refined style',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
  },
];

export const mockProducts = [
  {
    _id: '1',
    name: 'Oversized Linen Blazer',
    slug: 'oversized-linen-blazer',
    description: 'A relaxed yet refined oversized blazer crafted from premium linen. Features a single-button closure, patch pockets, and a beautifully draped silhouette perfect for layering.',
    price: 285,
    comparePrice: 350,
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800'],
    category: { _id: '3', name: 'Outerwear', slug: 'outerwear' },
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Black', 'Sand'],
    stock: 45,
    featured: true,
    isActive: true,
    rating: 4.8,
    numReviews: 124,
  },
  {
    _id: '2',
    name: 'Silk Midi Dress',
    slug: 'silk-midi-dress',
    description: 'Flowing silk charmeuse midi dress with a cowl neckline and adjustable spaghetti straps. An effortlessly elegant piece that transitions from day to evening.',
    price: 420,
    comparePrice: 480,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
    category: { _id: '4', name: 'Dresses', slug: 'dresses' },
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Champagne', 'Noir', 'Dusty Rose'],
    stock: 30,
    featured: true,
    isActive: true,
    rating: 4.9,
    numReviews: 89,
  },
  {
    _id: '3',
    name: 'Structured Cotton Tee',
    slug: 'structured-cotton-tee',
    description: 'The perfect foundational piece. Heavy-weight organic cotton tee with a structured shoulder and relaxed body. A wardrobe essential elevated.',
    price: 85,
    comparePrice: 0,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
    category: { _id: '1', name: 'Tops', slug: 'tops' },
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Heather Grey'],
    stock: 120,
    featured: true,
    isActive: true,
    rating: 4.7,
    numReviews: 256,
  },
  {
    _id: '4',
    name: 'Wide-Leg Tailored Trousers',
    slug: 'wide-leg-tailored-trousers',
    description: 'Impeccably tailored trousers with a wide, straight leg. High-rise waist with a subtle pleat detail and side zip. Crafted from premium wool blend.',
    price: 325,
    comparePrice: 400,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800'],
    category: { _id: '2', name: 'Bottoms', slug: 'bottoms' },
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Camel', 'Navy'],
    stock: 35,
    featured: true,
    isActive: true,
    rating: 4.6,
    numReviews: 145,
  },
  {
    _id: '5',
    name: 'Minimalist Leather Belt',
    slug: 'minimalist-leather-belt',
    description: 'Sleek leather belt with a minimalist buckle. Perfect to cinch dresses, blazers, or wear with tailored trousers. Crafted from Italian vegetable-tanned leather.',
    price: 165,
    comparePrice: 200,
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800'],
    category: { _id: '5', name: 'Accessories', slug: 'accessories' },
    sizes: ['One Size'],
    colors: ['Black', 'Cognac'],
    stock: 60,
    featured: false,
    isActive: true,
    rating: 4.8,
    numReviews: 98,
  },
  {
    _id: '6',
    name: 'Premium Sneaker',
    slug: 'premium-sneaker',
    description: 'Elevated minimal sneaker with a sleek silhouette. Cushioned sole for all-day comfort. Available in neutral tones that pair with everything.',
    price: 225,
    comparePrice: 280,
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'],
    category: { _id: '6', name: 'Footwear', slug: 'footwear' },
    sizes: ['5', '6', '7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black', 'Cream'],
    stock: 55,
    featured: false,
    isActive: true,
    rating: 4.7,
    numReviews: 172,
  },
];
