export const mockCategories = [
    {
        _id: '1',
        name: 'Tops',
        slug: 'tops',
        description: 'Elevated essentials for every occasion',
        image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
    },
    {
        _id: '2',
        name: 'Bottoms',
        slug: 'bottoms',
        description: 'Refined silhouettes from denim to tailored',
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    },
    {
        _id: '3',
        name: 'Outerwear',
        slug: 'outerwear',
        description: 'Statement pieces for layered looks',
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    },
    {
        _id: '4',
        name: 'Dresses',
        slug: 'dresses',
        description: 'From minimal to bold, day to night',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
    },
    {
        _id: '5',
        name: 'Accessories',
        slug: 'accessories',
        description: 'The finishing touch to complete your look',
        image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800',
    },
    {
        _id: '6',
        name: 'Footwear',
        slug: 'footwear',
        description: 'Step forward in refined style',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    },
];

export const mockProducts = [
    {
        _id: '1',
        name: 'Oversized Linen Blazer',
        slug: 'oversized-linen-blazer',
        description: 'A relaxed yet refined oversized blazer crafted from premium linen. Features a single-button closure, patch pockets, and a beautifully draped silhouette perfect for layering.',
        price: 285,
        comparePrice: 350,
        images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800'],
        category: { _id: '3', name: 'Outerwear', slug: 'outerwear' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Ivory', 'Black', 'Sand'],
        stock: 45,
        featured: true,
        isActive: true,
        rating: 4.8,
        numReviews: 124,
    },
    {
        _id: '2',
        name: 'Silk Midi Dress',
        slug: 'silk-midi-dress',
        description: 'Flowing silk charmeuse midi dress with a cowl neckline and adjustable spaghetti straps. An effortlessly elegant piece that transitions from day to evening.',
        price: 420,
        comparePrice: 480,
        images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
        category: { _id: '4', name: 'Dresses', slug: 'dresses' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Champagne', 'Noir', 'Dusty Rose'],
        stock: 30,
        featured: true,
        isActive: true,
        rating: 4.9,
        numReviews: 89,
    },
    {
        _id: '3',
        name: 'Structured Cotton Tee',
        slug: 'structured-cotton-tee',
        description: 'The perfect foundational piece. Heavy-weight organic cotton tee with a structured shoulder and relaxed body. A wardrobe essential elevated.',
        price: 85,
        comparePrice: 0,
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
        category: { _id: '1', name: 'Tops', slug: 'tops' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Black', 'Heather Grey'],
        stock: 120,
        featured: true,
        isActive: true,
        rating: 4.7,
        numReviews: 256,
    },
    {
        _id: '4',
        name: 'Wide-Leg Tailored Trousers',
        slug: 'wide-leg-tailored-trousers',
        description: 'Impeccably tailored trousers with a wide, straight leg. High-rise waist with a subtle pleat detail and side zip. Crafted from premium wool blend.',
        price: 325,
        comparePrice: 400,
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800'],
        category: { _id: '2', name: 'Bottoms', slug: 'bottoms' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Charcoal', 'Camel', 'Navy'],
        stock: 35,
        featured: true,
        isActive: true,
        rating: 4.6,
        numReviews: 145,
    },
    {
        _id: '5',
        name: 'Minimalist Leather Belt',
        slug: 'minimalist-leather-belt',
        description: 'Sleek leather belt with a minimalist buckle. Perfect to cinch dresses, blazers, or wear with tailored trousers. Crafted from Italian vegetable-tanned leather.',
        price: 165,
        comparePrice: 200,
        images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800'],
        category: { _id: '5', name: 'Accessories', slug: 'accessories' },
        sizes: ['One Size'],
        colors: ['Black', 'Cognac'],
        stock: 60,
        featured: false,
        isActive: true,
        rating: 4.8,
        numReviews: 98,
    },
    {
        _id: '6',
        name: 'Premium Sneaker',
        slug: 'premium-sneaker',
        description: 'Elevated minimal sneaker with a sleek silhouette. Cushioned sole for all-day comfort. Available in neutral tones that pair with everything.',
        price: 225,
        comparePrice: 280,
        images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'],
        category: { _id: '6', name: 'Footwear', slug: 'footwear' },
        sizes: ['5', '6', '7', '8', '9', '10', '11', '12'],
        colors: ['White', 'Black', 'Cream'],
        stock: 55,
        featured: false,
        isActive: true,
        rating: 4.7,
        numReviews: 172,
    },
    {
        _id: '7',
        name: 'Cashmere Knit Sweater',
        slug: 'cashmere-knit-sweater',
        description: 'Luxurious pure cashmere crewneck sweater in a timeless design. Soft, warm, and versatile for layering or wearing alone.',
        price: 395,
        comparePrice: 450,
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
        category: { _id: '1', name: 'Tops', slug: 'tops' },
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Ivory', 'Charcoal', 'Camel', 'Navy'],
        stock: 28,
        featured: true,
        isActive: true,
        rating: 4.9,
        numReviews: 203,
    },
    {
        _id: '8',
        name: 'High-Waist Denim Jeans',
        slug: 'high-waist-denim-jeans',
        description: 'Classic high-waist denim jeans with a straight leg cut. Premium raw denim that develops character over time. Perfect everyday essential.',
        price: 245,
        comparePrice: 300,
        images: ['https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800'],
        category: { _id: '2', name: 'Bottoms', slug: 'bottoms' },
        sizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
        colors: ['Indigo', 'Black', 'Light Wash'],
        stock: 72,
        featured: false,
        isActive: true,
        rating: 4.8,
        numReviews: 318,
    },
    {
        _id: '9',
        name: 'Wool Coat',
        slug: 'wool-coat',
        description: 'Timeless wool coat with a classic silhouette. Features button closure and side pockets. Perfect for transitional weather.',
        price: 525,
        comparePrice: 650,
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800'],
        category: { _id: '3', name: 'Outerwear', slug: 'outerwear' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Charcoal', 'Camel', 'Burgundy'],
        stock: 22,
        featured: true,
        isActive: true,
        rating: 4.9,
        numReviews: 156,
    },
    {
        _id: '10',
        name: 'Maxi Evening Gown',
        slug: 'maxi-evening-gown',
        description: 'Stunning maxi gown perfect for special occasions. Features elegant draping and a flattering silhouette.',
        price: 685,
        comparePrice: 800,
        images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
        category: { _id: '4', name: 'Dresses', slug: 'dresses' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Navy', 'Gold', 'Silver'],
        stock: 15,
        featured: true,
        isActive: true,
        rating: 4.8,
        numReviews: 92,
    },
    {
        _id: '11',
        name: 'Silk Scarf',
        slug: 'silk-scarf',
        description: 'Luxurious silk scarf with vibrant prints. Versatile piece that elevates any outfit.',
        price: 125,
        comparePrice: 150,
        images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800'],
        category: { _id: '5', name: 'Accessories', slug: 'accessories' },
        sizes: ['One Size'],
        colors: ['Multicolor', 'Blush', 'Forest Green'],
        stock: 95,
        featured: false,
        isActive: true,
        rating: 4.6,
        numReviews: 67,
    },
    {
        _id: '12',
        name: 'Leather Loafers',
        slug: 'leather-loafers',
        description: 'Timeless leather loafers with premium construction. Comfortable and versatile for both casual and formal occasions.',
        price: 295,
        comparePrice: 350,
        images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'],
        category: { _id: '6', name: 'Footwear', slug: 'footwear' },
        sizes: ['5', '6', '7', '8', '9', '10', '11', '12', '13'],
        colors: ['Black', 'Tan', 'Burgundy'],
        stock: 48,
        featured: false,
        isActive: true,
        rating: 4.7,
        numReviews: 143,
    },
    {
        _id: '13',
        name: 'Linen Button-Up Shirt',
        slug: 'linen-button-up-shirt',
        description: 'Lightweight linen shirt perfect for warm weather. Breathable fabric with a relaxed fit.',
        price: 155,
        comparePrice: 185,
        images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800'],
        category: { _id: '1', name: 'Tops', slug: 'tops' },
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Cream', 'Light Blue', 'Sage Green'],
        stock: 63,
        featured: false,
        isActive: true,
        rating: 4.5,
        numReviews: 89,
    },
    {
        _id: '14',
        name: 'Pleated Midi Skirt',
        slug: 'pleated-midi-skirt',
        description: 'Elegant pleated midi skirt with a high waist. Perfect for creating sophisticated, layered looks.',
        price: 215,
        comparePrice: 260,
        images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
        category: { _id: '2', name: 'Bottoms', slug: 'bottoms' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Burgundy', 'Sage', 'Cream'],
        stock: 42,
        featured: false,
        isActive: true,
        rating: 4.7,
        numReviews: 127,
    },
    {
        _id: '15',
        name: 'Trench Coat',
        slug: 'trench-coat',
        description: 'Classic trench coat with belted waist and functional pockets. Timeless piece for all seasons.',
        price: 445,
        comparePrice: 550,
        images: ['https://images.unsplash.com/photo-1539533057440-7bf6b1a76248?w=800'],
        category: { _id: '3', name: 'Outerwear', slug: 'outerwear' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Tan', 'Black', 'Navy'],
        stock: 35,
        featured: true,
        isActive: true,
        rating: 4.8,
        numReviews: 178,
    },
    {
        _id: '16',
        name: 'Cocktail Dress',
        slug: 'cocktail-dress',
        description: 'Chic cocktail dress perfect for parties and events. Features a flattering fit and elegant details.',
        price: 385,
        comparePrice: 450,
        images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
        category: { _id: '4', name: 'Dresses', slug: 'dresses' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Emerald', 'Rose Gold'],
        stock: 27,
        featured: false,
        isActive: true,
        rating: 4.8,
        numReviews: 103,
    },
    {
        _id: '17',
        name: 'Pearl Necklace',
        slug: 'pearl-necklace',
        description: 'Elegant pearl necklace with gold findings. Timeless accessory for any occasion.',
        price: 245,
        comparePrice: 300,
        images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800'],
        category: { _id: '5', name: 'Accessories', slug: 'accessories' },
        sizes: ['One Size'],
        colors: ['Gold', 'Silver'],
        stock: 38,
        featured: true,
        isActive: true,
        rating: 4.9,
        numReviews: 156,
    },
    {
        _id: '18',
        name: 'Boots',
        slug: 'leather-boots',
        description: 'Premium leather boots with comfortable heel. Perfect for any season and style.',
        price: 385,
        comparePrice: 480,
        images: ['https://images.unsplash.com/photo-1608256246200-53987f48f696?w=800'],
        category: { _id: '6', name: 'Footwear', slug: 'footwear' },
        sizes: ['5', '6', '7', '8', '9', '10', '11', '12'],
        colors: ['Black', 'Brown', 'Burgundy'],
        stock: 31,
        featured: true,
        isActive: true,
        rating: 4.8,
        numReviews: 201,
    },
];
