import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User';
import Category from './models/Category';
import Product from './models/Product';
import connectDB from './config/db';

dotenv.config();

const seedData = async () => {
  try {
    await connectDB();

    // Clear existing data
    await User.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});

    // Create admin user
    const admin = await User.create({
      name: 'Admin',
      email: 'admin@neuve.com',
      password: 'admin123',
      role: 'admin',
    });

    // Create test user
    await User.create({
      name: 'Test User',
      email: 'user@neuve.com',
      password: 'user123',
      role: 'user',
    });

    // Create categories
    const categories = await Category.insertMany([
      { name: 'Tops', slug: 'tops', description: 'Elevated essentials for every occasion', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800' },
      { name: 'Bottoms', slug: 'bottoms', description: 'Refined silhouettes from denim to tailored', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800' },
      { name: 'Outerwear', slug: 'outerwear', description: 'Statement pieces for layered looks', image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800' },
      { name: 'Dresses', slug: 'dresses', description: 'From minimal to bold, day to night', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800' },
      { name: 'Accessories', slug: 'accessories', description: 'The finishing touch to complete your look', image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800' },
      { name: 'Footwear', slug: 'footwear', description: 'Step forward in refined style', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800' },
    ]);

    // Create products
    const products = [
      {
        name: 'Oversized Linen Blazer',
        slug: 'oversized-linen-blazer',
        description: 'A relaxed yet refined oversized blazer crafted from premium linen. Features a single-button closure, patch pockets, and a beautifully draped silhouette perfect for layering.',
        price: 285,
        comparePrice: 350,
        images: [
          'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
          'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
        ],
        category: categories[2]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Ivory', 'Black', 'Sand'],
        stock: 45,
        featured: true,
        rating: 4.8,
        numReviews: 124,
      },
      {
        name: 'Silk Midi Dress',
        slug: 'silk-midi-dress',
        description: 'Flowing silk charmeuse midi dress with a cowl neckline and adjustable spaghetti straps. An effortlessly elegant piece that transitions from day to evening.',
        price: 420,
        images: [
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
        ],
        category: categories[3]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Champagne', 'Noir', 'Dusty Rose'],
        stock: 30,
        featured: true,
        rating: 4.9,
        numReviews: 89,
      },
      {
        name: 'Structured Cotton Tee',
        slug: 'structured-cotton-tee',
        description: 'The perfect foundational piece. Heavy-weight organic cotton tee with a structured shoulder and relaxed body. A wardrobe essential elevated.',
        price: 85,
        images: [
          'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
        ],
        category: categories[0]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Black', 'Heather Grey'],
        stock: 120,
        featured: true,
        rating: 4.7,
        numReviews: 256,
      },
      {
        name: 'Wide-Leg Tailored Trousers',
        slug: 'wide-leg-tailored-trousers',
        description: 'Impeccably tailored wide-leg trousers in a wool-blend fabric. Features a high waist, pressed crease, and flowing silhouette. The epitome of modern sophistication.',
        price: 245,
        images: [
          'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
          'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
        ],
        category: categories[1]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Charcoal', 'Camel'],
        stock: 60,
        featured: true,
        rating: 4.6,
        numReviews: 178,
      },
      {
        name: 'Cashmere Knit Pullover',
        slug: 'cashmere-knit-pullover',
        description: 'Luxuriously soft pure cashmere pullover with a relaxed fit and ribbed trims. An investment piece designed to be cherished season after season.',
        price: 380,
        comparePrice: 450,
        images: [
          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
          'https://images.unsplash.com/photo-1608234808654-2a8875faa7fd?w=800',
        ],
        category: categories[0]._id,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Oatmeal', 'Black', 'Navy'],
        stock: 35,
        featured: true,
        rating: 4.9,
        numReviews: 67,
      },
      {
        name: 'Leather Minimalist Belt',
        slug: 'leather-minimalist-belt',
        description: 'Hand-crafted Italian leather belt with a sleek brushed silver buckle. Minimal design that complements any outfit with understated elegance.',
        price: 120,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
        ],
        category: categories[4]._id,
        sizes: ['S', 'M', 'L'],
        colors: ['Black', 'Tan', 'Dark Brown'],
        stock: 80,
        featured: false,
        rating: 4.5,
        numReviews: 95,
      },
      {
        name: 'Wool Overcoat',
        slug: 'wool-overcoat',
        description: 'A timeless double-breasted overcoat in premium Italian wool. Features a notch lapel, back vent, and satin lining. The definitive outerwear statement.',
        price: 595,
        comparePrice: 750,
        images: [
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
          'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800',
        ],
        category: categories[2]._id,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Camel', 'Grey'],
        stock: 25,
        featured: true,
        rating: 4.8,
        numReviews: 44,
      },
      {
        name: 'Minimal Leather Sneakers',
        slug: 'minimal-leather-sneakers',
        description: 'Clean, minimal leather sneakers crafted from full-grain Italian leather with a hand-stitched sole. Where luxury meets everyday wearability.',
        price: 265,
        images: [
          'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
          'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800',
        ],
        category: categories[5]._id,
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['White', 'Black', 'Off-White'],
        stock: 50,
        featured: true,
        rating: 4.7,
        numReviews: 132,
      },
      {
        name: 'Draped Jersey Top',
        slug: 'draped-jersey-top',
        description: 'A fluid jersey top with an asymmetric drape and sculptural neckline. Effortless elegance in a single piece.',
        price: 145,
        images: [
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800',
        ],
        category: categories[0]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Cream', 'Olive'],
        stock: 55,
        featured: false,
        rating: 4.4,
        numReviews: 78,
      },
      {
        name: 'High-Waist Straight Jeans',
        slug: 'high-waist-straight-jeans',
        description: 'Premium Japanese selvedge denim in a high-waisted straight leg cut. Raw indigo with natural fading potential. Built to age beautifully.',
        price: 195,
        images: [
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800',
          'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
        ],
        category: categories[1]._id,
        sizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
        colors: ['Raw Indigo', 'Washed Black', 'Stone'],
        stock: 70,
        featured: false,
        rating: 4.6,
        numReviews: 201,
      },
      {
        name: 'Sculpted Heel Boots',
        slug: 'sculpted-heel-boots',
        description: 'Architectural ankle boots with a sculpted heel and buttery soft leather. A bold statement piece that elevates every outfit.',
        price: 445,
        images: [
          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
        ],
        category: categories[5]._id,
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Black', 'Espresso'],
        stock: 20,
        featured: false,
        rating: 4.8,
        numReviews: 56,
      },
      {
        name: 'Wrap Midi Skirt',
        slug: 'wrap-midi-skirt',
        description: 'A fluid wrap midi skirt in silk-blend fabric. Features a self-tie waist and elegant drape that moves beautifully with every step.',
        price: 175,
        images: [
          'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
        ],
        category: categories[1]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Burgundy', 'Forest Green'],
        stock: 40,
        featured: false,
        rating: 4.5,
        numReviews: 92,
      },
      // ── 20 NEW PRODUCTS ──
      {
        name: 'Ribbed Knit Tank Top',
        slug: 'ribbed-knit-tank-top',
        description: 'A sleek ribbed-knit tank with a slim silhouette and modern square neckline. Crafted from a soft cotton-modal blend for all-day comfort.',
        price: 65,
        images: [
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800',
          'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=800',
        ],
        category: categories[0]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Black', 'Sage'],
        stock: 100,
        featured: false,
        rating: 4.5,
        numReviews: 143,
      },
      {
        name: 'Poplin Button-Down Shirt',
        slug: 'poplin-button-down-shirt',
        description: 'A crisp organic cotton poplin shirt with a relaxed boyfriend fit, curved hem, and mother-of-pearl buttons. Perfectly polished yet effortless.',
        price: 135,
        comparePrice: 165,
        images: [
          'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800',
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
        ],
        category: categories[0]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Light Blue', 'Pale Pink'],
        stock: 75,
        featured: true,
        rating: 4.7,
        numReviews: 198,
      },
      {
        name: 'Merino Wool Turtleneck',
        slug: 'merino-wool-turtleneck',
        description: 'Ultra-fine merino wool turtleneck with a smooth hand feel and lightweight warmth. A refined layering essential for the cooler months.',
        price: 195,
        images: [
          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
          'https://images.unsplash.com/photo-1608234808654-2a8875faa7fd?w=800',
        ],
        category: categories[0]._id,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Cream', 'Burgundy', 'Forest Green'],
        stock: 55,
        featured: false,
        rating: 4.8,
        numReviews: 87,
      },
      {
        name: 'Cargo Utility Trousers',
        slug: 'cargo-utility-trousers',
        description: 'Modern utility-inspired cargo trousers in washed cotton twill. Relaxed tapered fit with patch pockets and an adjustable waistband.',
        price: 165,
        images: [
          'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
          'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
        ],
        category: categories[1]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Khaki', 'Black', 'Olive'],
        stock: 65,
        featured: false,
        rating: 4.4,
        numReviews: 112,
      },
      {
        name: 'Pleated Wide-Leg Pants',
        slug: 'pleated-wide-leg-pants',
        description: 'Elevated pleated trousers with a dramatic wide leg in a fluid crepe fabric. High-waisted with a concealed side zip for a clean front.',
        price: 215,
        images: [
          'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=800',
          'https://images.unsplash.com/photo-1551854838-212c50b4c184?w=800',
        ],
        category: categories[1]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Navy', 'Ivory'],
        stock: 40,
        featured: true,
        rating: 4.6,
        numReviews: 74,
      },
      {
        name: 'Relaxed Linen Shorts',
        slug: 'relaxed-linen-shorts',
        description: 'Breezy linen shorts with a drawstring waist and relaxed fit. The ideal warm-weather essential for effortless weekend style.',
        price: 95,
        images: [
          'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800',
        ],
        category: categories[1]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Sand', 'White', 'Sky Blue'],
        stock: 90,
        featured: false,
        rating: 4.3,
        numReviews: 66,
      },
      {
        name: 'Quilted Bomber Jacket',
        slug: 'quilted-bomber-jacket',
        description: 'A contemporary quilted bomber jacket with a tonal zip, ribbed cuffs, and a lightweight insulated fill. Lightweight enough for transitional seasons.',
        price: 325,
        comparePrice: 400,
        images: [
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
          'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800',
        ],
        category: categories[2]._id,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Olive', 'Navy'],
        stock: 30,
        featured: true,
        rating: 4.7,
        numReviews: 58,
      },
      {
        name: 'Trench Coat',
        slug: 'classic-trench-coat',
        description: 'A reimagined classic trench coat in water-resistant cotton gabardine. Double-breasted with a storm flap, removable belt, and checked lining.',
        price: 495,
        comparePrice: 620,
        images: [
          'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800',
          'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800',
        ],
        category: categories[2]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Khaki', 'Black', 'Navy'],
        stock: 20,
        featured: true,
        rating: 4.9,
        numReviews: 41,
      },
      {
        name: 'Satin Slip Dress',
        slug: 'satin-slip-dress',
        description: 'A bias-cut satin slip dress with delicate lace trim and adjustable straps. Luxurious simplicity for cocktail evenings and special occasions.',
        price: 310,
        images: [
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
        ],
        category: categories[3]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Noir', 'Champagne', 'Emerald'],
        stock: 25,
        featured: true,
        rating: 4.8,
        numReviews: 63,
      },
      {
        name: 'Cotton Shirt Dress',
        slug: 'cotton-shirt-dress',
        description: 'A relaxed cotton poplin shirt dress with a detachable self-tie belt, chest pockets, and a midi-length hem. Versatile and timeless.',
        price: 185,
        images: [
          'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=800',
          'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800',
        ],
        category: categories[3]._id,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Khaki', 'Chambray Blue'],
        stock: 50,
        featured: false,
        rating: 4.5,
        numReviews: 109,
      },
      {
        name: 'Knit Bodycon Dress',
        slug: 'knit-bodycon-dress',
        description: 'A sleek ribbed-knit bodycon dress with a mock neck and midi length. Sculpting fit in a stretchy viscose blend for sophisticated evenings out.',
        price: 225,
        images: [
          'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=800',
        ],
        category: categories[3]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Chocolate', 'Deep Red'],
        stock: 35,
        featured: false,
        rating: 4.6,
        numReviews: 82,
      },
      {
        name: 'Oversized Wool Scarf',
        slug: 'oversized-wool-scarf',
        description: 'A generously sized scarf in brushed Italian wool. Soft enough to drape as a shawl, warm enough to brave the coldest days. Finished with fringed edges.',
        price: 145,
        images: [
          'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800',
          'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800',
        ],
        category: categories[4]._id,
        sizes: ['One Size'],
        colors: ['Camel', 'Grey', 'Black', 'Burgundy'],
        stock: 60,
        featured: false,
        rating: 4.7,
        numReviews: 121,
      },
      {
        name: 'Gold Chain Necklace',
        slug: 'gold-chain-necklace',
        description: 'An 18k gold-plated chain necklace with a minimalist link design. Hypoallergenic and tarnish-resistant. Layer it or let it stand alone.',
        price: 89,
        images: [
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
        ],
        category: categories[4]._id,
        sizes: ['One Size'],
        colors: ['Gold', 'Silver'],
        stock: 110,
        featured: true,
        rating: 4.4,
        numReviews: 204,
      },
      {
        name: 'Leather Crossbody Bag',
        slug: 'leather-crossbody-bag',
        description: 'A compact crossbody bag in pebbled Italian leather with an adjustable strap, magnetic closure, and interior card slots. Hands-free elegance.',
        price: 275,
        comparePrice: 340,
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
          'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
        ],
        category: categories[4]._id,
        sizes: ['One Size'],
        colors: ['Black', 'Tan', 'Burgundy'],
        stock: 45,
        featured: true,
        rating: 4.8,
        numReviews: 97,
      },
      {
        name: 'Canvas Tote Bag',
        slug: 'canvas-tote-bag',
        description: 'An oversized organic canvas tote with reinforced leather handles and an interior zip pocket. Durable enough for daily use, stylish enough for anywhere.',
        price: 78,
        images: [
          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800',
        ],
        category: categories[4]._id,
        sizes: ['One Size'],
        colors: ['Natural', 'Black', 'Navy'],
        stock: 130,
        featured: false,
        rating: 4.3,
        numReviews: 176,
      },
      {
        name: 'Suede Loafers',
        slug: 'suede-loafers',
        description: 'Classic penny loafers in buttery Italian suede with a blake-stitched leather sole. Polished enough for the office, comfortable enough for all day.',
        price: 235,
        images: [
          'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800',
          'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800',
        ],
        category: categories[5]._id,
        sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
        colors: ['Tan', 'Black', 'Navy'],
        stock: 40,
        featured: false,
        rating: 4.6,
        numReviews: 88,
      },
      {
        name: 'Strappy Heeled Sandals',
        slug: 'strappy-heeled-sandals',
        description: 'Elegant strappy sandals with a sculpted 80mm heel in nappa leather. Delicate ankle strap with a gold-tone buckle. Day-to-night versatility.',
        price: 295,
        images: [
          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
          'https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?w=800',
        ],
        category: categories[5]._id,
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Black', 'Nude', 'Gold'],
        stock: 30,
        featured: true,
        rating: 4.7,
        numReviews: 72,
      },
      {
        name: 'Platform Canvas Sneakers',
        slug: 'platform-canvas-sneakers',
        description: 'Organic cotton canvas sneakers on a chunky platform sole. Vulcanized rubber outsole for durability and a bold streetwear-meets-luxury aesthetic.',
        price: 155,
        images: [
          'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800',
          'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
        ],
        category: categories[5]._id,
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
        colors: ['White', 'Black', 'Sage Green'],
        stock: 70,
        featured: false,
        rating: 4.5,
        numReviews: 134,
      },
      {
        name: 'Denim Trucker Jacket',
        slug: 'denim-trucker-jacket',
        description: 'A heritage-inspired trucker jacket in rigid selvedge denim. Designed to develop a unique fade pattern over time. Copper hardware and a boxy silhouette.',
        price: 225,
        comparePrice: 280,
        images: [
          'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800',
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
        ],
        category: categories[2]._id,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Raw Indigo', 'Washed Black'],
        stock: 35,
        featured: false,
        rating: 4.6,
        numReviews: 91,
      },
      {
        name: 'Linen Maxi Dress',
        slug: 'linen-maxi-dress',
        description: 'A breezy floor-length linen dress with a tiered skirt, smocked bust, and adjustable shoulder ties. Effortless summer elegance.',
        price: 245,
        images: [
          'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800',
          'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=800',
        ],
        category: categories[3]._id,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['White', 'Terracotta', 'Sage'],
        stock: 40,
        featured: false,
        rating: 4.7,
        numReviews: 58,
      },
    ];

    await Product.insertMany(products);

    console.log('Data seeded successfully!');
    console.log('Admin: admin@neuve.com / admin123');
    console.log('User: user@neuve.com / user123');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedData();
